services:
  cache:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

  url-shortener:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: cache:6379
      APP_URI: ${APP_URI}
      APP_TITLE: ${APP_TITLE-Url Shortener}
    depends_on:
      - cache

volumes:
  cache:
    driver: local